export const dummyStats = {
  totalSale: 2450000,
  totalPurchase: 1820000,
  totalProfit: 630000,
  totalChannels: 48,
  soldChannels: 31,
  availableChannels: 12,
  hackedChannels: 5,
};

export const monthlySalesData = [
  { month: "Jan", sales: 320000, purchases: 210000, profit: 110000 },
  { month: "Feb", sales: 280000, purchases: 190000, profit: 90000 },
  { month: "Mar", sales: 450000, purchases: 310000, profit: 140000 },
  { month: "Apr", sales: 390000, purchases: 270000, profit: 120000 },
  { month: "May", sales: 520000, purchases: 380000, profit: 140000 },
  { month: "Jun", sales: 490000, purchases: 460000, profit: 30000 },
];

export const recentChannels = [
  { id: 1, name: "TechVault PK", niche: "Technology", subscribers: "125K", salePrice: 380000, status: "sold" },
  { id: 2, name: "CookingWithNadia", niche: "Food", subscribers: "89K", salePrice: 210000, status: "available" },
  { id: 3, name: "CricketZone", niche: "Sports", subscribers: "340K", salePrice: 750000, status: "available" },
  { id: 4, name: "DailyVlogs786", niche: "Lifestyle", subscribers: "55K", salePrice: 130000, status: "sold" },
  { id: 5, name: "IslamicReminders", niche: "Religion", subscribers: "210K", salePrice: 490000, status: "available" },
];

export const navLinks = [
  { label: "Dashboard", icon: "LayoutDashboard", path: "/" },
  { label: "Channels", icon: "Video", path: "/channels" },
  { label: "Purchases", icon: "ShoppingCart", path: "/purchases" },
  { label: "Sales", icon: "TrendingUp", path: "/sales" },
  { label: "Reports", icon: "BarChart2", path: "/reports" },
  { label: "Hacked", icon: "ShieldAlert", path: "/hacked" },
];

export const channelsData = [
  {
    id: 1, channelName: "TechVault PK", channelEmail: "techvaultpk@gmail.com",
    primaryMail: "owner.techvault@gmail.com", category: "Tech",
    channelNiche: "Gadgets & Reviews", channelSubscribers: 125000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 280000, salePrice: 380000, sellerName: "Ahmed Raza",
    buyerName: "Usman Tariq", buyerContact: "+92 301 2345678", soldAt: "2024-03-15",
    createdAt: "2024-01-15", contentType: "Long-form",
    verificationStatus: true, views: 4200000, totalVideos: 312,
    brandName: "TechVault", channelUrl: "youtube.com/techvaultpk",
  },
  {
    id: 2, channelName: "CookingWithNadia", channelEmail: "cookingnadia@gmail.com",
    primaryMail: "nadia.kitchen@gmail.com", category: "Food",
    channelNiche: "Pakistani Recipes", channelSubscribers: 89000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 150000, salePrice: 210000, sellerName: "Nadia Hussain",
    createdAt: "2024-02-03", contentType: "Long-form",
    verificationStatus: false, views: 2800000, totalVideos: 198,
    brandName: "Nadia Kitchen", channelUrl: "youtube.com/cookingnadia",
  },
  {
    id: 3, channelName: "CricketZone", channelEmail: "cricketzone.pk@gmail.com",
    primaryMail: "admin.cricketzone@gmail.com", category: "Sports",
    channelNiche: "Cricket Highlights", channelSubscribers: 340000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 550000, salePrice: 750000, sellerName: "Usman Malik",
    createdAt: "2024-01-22", contentType: "Short-form",
    verificationStatus: true, views: 18000000, totalVideos: 870,
    brandName: "CricketZone", channelUrl: "youtube.com/cricketzonepk",
  },
  {
    id: 4, channelName: "DailyVlogs786", channelEmail: "dailyvlogs786@gmail.com",
    primaryMail: "vlogs786@gmail.com", category: "Lifestyle",
    channelNiche: "Daily Life", channelSubscribers: 55000,
    monetizationStatus: "Not Monetized", status: "hacked",
    purchasePrice: 90000, salePrice: 130000, sellerName: "Bilal Chaudhry",
    createdAt: "2024-03-10", contentType: "Long-form",
    verificationStatus: false, views: 980000, totalVideos: 245,
    brandName: "Vlogs786", channelUrl: "youtube.com/dailyvlogs786",
  },
  {
    id: 5, channelName: "IslamicReminders", channelEmail: "islamicreminders@gmail.com",
    primaryMail: "islamic.channel@gmail.com", category: "Education",
    channelNiche: "Islamic Content", channelSubscribers: 210000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 320000, salePrice: 490000, sellerName: "Tariq Jameel",
    createdAt: "2024-02-18", contentType: "Long-form",
    verificationStatus: true, views: 9500000, totalVideos: 432,
    brandName: "Islamic Reminders", channelUrl: "youtube.com/islamicreminderspk",
  },
  {
    id: 6, channelName: "GamersArena", channelEmail: "gamersarena.pk@gmail.com",
    primaryMail: "arena.gaming@gmail.com", category: "Gaming",
    channelNiche: "Mobile Gaming", channelSubscribers: 480000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 700000, salePrice: 950000, sellerName: "Hamza Sheikh",
    buyerName: "Bilal Javed", buyerContact: "+92 321 9876543", soldAt: "2024-04-20",
    createdAt: "2024-01-08", contentType: "Long-form",
    verificationStatus: true, views: 22000000, totalVideos: 560,
    brandName: "GamersArena", channelUrl: "youtube.com/gamersarenapk",
  },
  {
    id: 7, channelName: "FinanceTips PK", channelEmail: "financetips.pk@gmail.com",
    primaryMail: "finance.tips.pk@gmail.com", category: "Finance",
    channelNiche: "Personal Finance", channelSubscribers: 72000,
    monetizationStatus: "Pending", status: "available",
    purchasePrice: 120000, salePrice: 175000, sellerName: "Kamran Akbar",
    createdAt: "2024-04-02", contentType: "Long-form",
    verificationStatus: false, views: 1800000, totalVideos: 134,
    brandName: "FinanceTips", channelUrl: "youtube.com/financetipspk",
  },
  {
    id: 8, channelName: "EntertainMe PK", channelEmail: "entertainmepk@gmail.com",
    primaryMail: "entertain.me.pk@gmail.com", category: "Entertainment",
    channelNiche: "Comedy Skits", channelSubscribers: 1200000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 1200000, salePrice: 1800000, sellerName: "Zara Siddiqui",
    buyerName: "Imran Ahmed", buyerContact: "+92 333 5678901", soldAt: "2024-02-10",
    createdAt: "2024-01-30", contentType: "Short-form",
    verificationStatus: true, views: 85000000, totalVideos: 2100,
    brandName: "EntertainMe", channelUrl: "youtube.com/entertainmepk",
  },
  {
    id: 9, channelName: "FitnessFirst PK", channelEmail: "fitnessfirst.pk@gmail.com",
    primaryMail: "fitness.first.owner@gmail.com", category: "Lifestyle",
    channelNiche: "Workout & Health", channelSubscribers: 95000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 160000, salePrice: 240000, sellerName: "Sara Malik",
    createdAt: "2024-03-25", contentType: "Long-form",
    verificationStatus: false, views: 3400000, totalVideos: 287,
    brandName: "FitnessFirst", channelUrl: "youtube.com/fitnessfirstpk",
  },
  {
    id: 10, channelName: "KidsLearningHub", channelEmail: "kidslearning.hub@gmail.com",
    primaryMail: "kids.hub.owner@gmail.com", category: "Education",
    channelNiche: "Kids Education", channelSubscribers: 670000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 800000, salePrice: 1100000, sellerName: "Fatima Zahra",
    buyerName: "Hira Baig", buyerContact: "+92 315 4567890", soldAt: "2024-04-05",
    createdAt: "2024-02-10", contentType: "Long-form",
    verificationStatus: true, views: 42000000, totalVideos: 920,
    brandName: "KidsHub", channelUrl: "youtube.com/kidslearninghub",
  },
  {
    id: 11, channelName: "TravelPakistan", channelEmail: "travelpakistan@gmail.com",
    primaryMail: "travel.pk.owner@gmail.com", category: "Lifestyle",
    channelNiche: "Travel & Tourism", channelSubscribers: 135000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 220000, salePrice: 320000, sellerName: "Hassan Mirza",
    createdAt: "2024-04-15", contentType: "Long-form",
    verificationStatus: false, views: 5200000, totalVideos: 198,
    brandName: "TravelPK", channelUrl: "youtube.com/travelpakistan",
  },
  {
    id: 12, channelName: "MusicVibes PK", channelEmail: "musicvibes.pk@gmail.com",
    primaryMail: "musicvibes.owner@gmail.com", category: "Entertainment",
    channelNiche: "Music & Covers", channelSubscribers: 520000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 600000, salePrice: 850000, sellerName: "Asad Khan",
    buyerName: "Kashif Mehmood", buyerContact: "+92 300 1234567", soldAt: "2024-03-28",
    createdAt: "2024-01-05", contentType: "Short-form",
    verificationStatus: true, views: 31000000, totalVideos: 1450,
    brandName: "MusicVibes", channelUrl: "youtube.com/musicvibespk",
  },
  {
    id: 13, channelName: "NewsFlashPK", channelEmail: "newsflash.pk@gmail.com",
    primaryMail: "newsflash.admin@gmail.com", category: "Entertainment",
    channelNiche: "News & Current Affairs", channelSubscribers: 890000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 950000, salePrice: 1350000, sellerName: "Rizwan Ahmed",
    createdAt: "2024-03-01", contentType: "Short-form",
    verificationStatus: true, views: 67000000, totalVideos: 3200,
    brandName: "NewsFlash", channelUrl: "youtube.com/newsflashpk",
  },
  {
    id: 14, channelName: "ChefKamran", channelEmail: "chefkamran.official@gmail.com",
    primaryMail: "kamran.chef@gmail.com", category: "Food",
    channelNiche: "BBQ & Grilling", channelSubscribers: 48000,
    monetizationStatus: "Not Monetized", status: "available",
    purchasePrice: 60000, salePrice: 90000, sellerName: "Kamran Butt",
    createdAt: "2024-05-10", contentType: "Long-form",
    verificationStatus: false, views: 820000, totalVideos: 87,
    brandName: "Chef Kamran", channelUrl: "youtube.com/chefkamran",
  },
  {
    id: 15, channelName: "PSLHighlights", channelEmail: "psl.highlights@gmail.com",
    primaryMail: "psl.official.channel@gmail.com", category: "Sports",
    channelNiche: "PSL Cricket", channelSubscribers: 2000000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 1500000, salePrice: 2000000, sellerName: "Imran Shah",
    buyerName: "Fahad Mustafa", buyerContact: "+92 312 8765432", soldAt: "2024-01-18",
    createdAt: "2024-01-01", contentType: "Short-form",
    verificationStatus: true, views: 200000000, totalVideos: 5600,
    brandName: "PSL Highlights", channelUrl: "youtube.com/pslhighlights",
  },
  {
    id: 16, channelName: "AutoZonePK", channelEmail: "autozone.pk@gmail.com",
    primaryMail: "autozone.admin@gmail.com", category: "Tech",
    channelNiche: "Cars & Bikes", channelSubscribers: 165000,
    monetizationStatus: "Monetized", status: "hacked",
    purchasePrice: 250000, salePrice: 380000, sellerName: "Faisal Qureshi",
    createdAt: "2024-02-28", contentType: "Long-form",
    verificationStatus: true, views: 7800000, totalVideos: 345,
    brandName: "AutoZone", channelUrl: "youtube.com/autozonepk",
  },
  {
    id: 17, channelName: "QuranInUrdu", channelEmail: "quranurdu@gmail.com",
    primaryMail: "quran.urdu.owner@gmail.com", category: "Education",
    channelNiche: "Quran Translation", channelSubscribers: 380000,
    monetizationStatus: "Pending", status: "available",
    purchasePrice: 400000, salePrice: 580000, sellerName: "Mufti Saeed",
    createdAt: "2024-04-20", contentType: "Long-form",
    verificationStatus: true, views: 14500000, totalVideos: 620,
    brandName: "QuranUrdu", channelUrl: "youtube.com/quranurdu",
  },
  {
    id: 18, channelName: "ComedyKlub", channelEmail: "comedyklub.pk@gmail.com",
    primaryMail: "comedy.klub@gmail.com", category: "Entertainment",
    channelNiche: "Pakistani Comedy", channelSubscribers: 750000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 850000, salePrice: 1200000, sellerName: "Danish Taimoor",
    buyerName: "Naveed Anjum", buyerContact: "+92 345 6789012", soldAt: "2024-05-12",
    createdAt: "2024-02-14", contentType: "Short-form",
    verificationStatus: true, views: 55000000, totalVideos: 1890,
    brandName: "ComedyKlub", channelUrl: "youtube.com/comedyklubpk",
  },
  {
    id: 19, channelName: "UrduPoetry", channelEmail: "urdupoetry.official@gmail.com",
    primaryMail: "poetry.urdu.owner@gmail.com", category: "Entertainment",
    channelNiche: "Poetry & Shayari", channelSubscribers: 220000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 300000, salePrice: 440000, sellerName: "Mahira Khalid",
    createdAt: "2024-05-05", contentType: "Short-form",
    verificationStatus: false, views: 10200000, totalVideos: 780,
    brandName: "Urdu Poetry", channelUrl: "youtube.com/urdupoetry",
  },
  {
    id: 20, channelName: "MobileWorldPK", channelEmail: "mobileworld.pk@gmail.com",
    primaryMail: "mobile.world.owner@gmail.com", category: "Tech",
    channelNiche: "Smartphone Reviews", channelSubscribers: 195000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 290000, salePrice: 420000, sellerName: "Waqar Hassan",
    buyerName: "Saba Qamar", buyerContact: "+92 311 2345678", soldAt: "2024-04-15",
    createdAt: "2024-03-18", contentType: "Long-form",
    verificationStatus: true, views: 8900000, totalVideos: 412,
    brandName: "MobileWorld", channelUrl: "youtube.com/mobileworldpk",
  },
  {
    id: 21, channelName: "FarmingWithAli", channelEmail: "farmingwithali@gmail.com",
    primaryMail: "ali.farming@gmail.com", category: "Other",
    channelNiche: "Modern Farming", channelSubscribers: 32000,
    monetizationStatus: "Not Monetized", status: "available",
    purchasePrice: 45000, salePrice: 70000, sellerName: "Ali Hassan",
    createdAt: "2024-06-01", contentType: "Long-form",
    verificationStatus: false, views: 540000, totalVideos: 65,
    brandName: "FarmingAli", channelUrl: "youtube.com/farmingwithali",
  },
  {
    id: 22, channelName: "GamingBattleground", channelEmail: "gamingbg.pk@gmail.com",
    primaryMail: "gaming.bg@gmail.com", category: "Gaming",
    channelNiche: "FPS Gaming", channelSubscribers: 310000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 420000, salePrice: 620000, sellerName: "Shahzaib Noor",
    createdAt: "2024-04-08", contentType: "Long-form",
    verificationStatus: true, views: 15600000, totalVideos: 498,
    brandName: "BattlegroundPK", channelUrl: "youtube.com/gamingbattleground",
  },
  {
    id: 23, channelName: "DIYHomeDecor", channelEmail: "diyhome.pk@gmail.com",
    primaryMail: "diy.homedecor@gmail.com", category: "Lifestyle",
    channelNiche: "Home Decoration", channelSubscribers: 68000,
    monetizationStatus: "Pending", status: "available",
    purchasePrice: 95000, salePrice: 145000, sellerName: "Ayesha Farooq",
    createdAt: "2024-05-20", contentType: "Long-form",
    verificationStatus: false, views: 1900000, totalVideos: 143,
    brandName: "DIYHome", channelUrl: "youtube.com/diyhomepk",
  },
  {
    id: 24, channelName: "CryptoTalkPK", channelEmail: "cryptotalk.pk@gmail.com",
    primaryMail: "crypto.pk.owner@gmail.com", category: "Finance",
    channelNiche: "Crypto & Blockchain", channelSubscribers: 115000,
    monetizationStatus: "Monetized", status: "hacked",
    purchasePrice: 180000, salePrice: 270000, sellerName: "Omar Farhan",
    createdAt: "2024-03-05", contentType: "Long-form",
    verificationStatus: false, views: 4400000, totalVideos: 228,
    brandName: "CryptoTalk", channelUrl: "youtube.com/cryptotalkpk",
  },
  {
    id: 25, channelName: "KarachiStreetFood", channelEmail: "karachistreet@gmail.com",
    primaryMail: "karachi.food.admin@gmail.com", category: "Food",
    channelNiche: "Street Food Tours", channelSubscribers: 430000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 520000, salePrice: 780000, sellerName: "Adnan Siddiqui",
    buyerName: "Amir Khan", buyerContact: "+92 322 3456789", soldAt: "2024-03-05",
    createdAt: "2024-01-28", contentType: "Short-form",
    verificationStatus: true, views: 28000000, totalVideos: 920,
    brandName: "KarachiFood", channelUrl: "youtube.com/karachistreetfood",
  },
  {
    id: 26, channelName: "EduMathPK", channelEmail: "edumath.pk@gmail.com",
    primaryMail: "math.edu.owner@gmail.com", category: "Education",
    channelNiche: "Math & Science", channelSubscribers: 155000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 220000, salePrice: 330000, sellerName: "Sana Arif",
    createdAt: "2024-06-15", contentType: "Long-form",
    verificationStatus: true, views: 6200000, totalVideos: 375,
    brandName: "EduMath", channelUrl: "youtube.com/edumathpk",
  },
  {
    id: 27, channelName: "BeautyByZara", channelEmail: "beautyzara.pk@gmail.com",
    primaryMail: "zara.beauty@gmail.com", category: "Lifestyle",
    channelNiche: "Beauty & Makeup", channelSubscribers: 260000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 350000, salePrice: 510000, sellerName: "Zara Noor",
    buyerName: "Mehwish Hayat", buyerContact: "+92 303 4567890", soldAt: "2024-05-25",
    createdAt: "2024-02-22", contentType: "Long-form",
    verificationStatus: false, views: 12000000, totalVideos: 310,
    brandName: "BeautyZara", channelUrl: "youtube.com/beautybyzara",
  },
  // ── Pending (in stock, awaiting sale) ────────────────────────────────────────
  {
    id: 28, channelName: "TravelDiariesPK", channelEmail: "traveldiaries.pk@gmail.com",
    primaryMail: "travel.diaries.owner@gmail.com", category: "Lifestyle",
    channelNiche: "Travel Vlogs", channelSubscribers: 78000,
    monetizationStatus: "Monetized", status: "pending",
    purchasePrice: 145000, salePrice: 220000, sellerName: "Hassan Ali",
    createdAt: "2024-06-10", contentType: "Long-form",
    verificationStatus: false, views: 2100000, totalVideos: 112,
    brandName: "TravelPK", channelUrl: "youtube.com/traveldiariespk",
    ownershipStatus: "Changed",
  },
  {
    id: 29, channelName: "HealthFirst PK", channelEmail: "healthfirst.pk@gmail.com",
    primaryMail: "health.first.pk@gmail.com", category: "Lifestyle",
    channelNiche: "Fitness & Wellness", channelSubscribers: 54000,
    monetizationStatus: "Not Monetized", status: "pending",
    purchasePrice: 85000, salePrice: 130000, sellerName: "Sara Baig",
    createdAt: "2024-06-18", contentType: "Long-form",
    verificationStatus: false, views: 1400000, totalVideos: 89,
    brandName: "HealthFirst", channelUrl: "youtube.com/healthfirstpk",
    ownershipStatus: "Pending",
  },
  {
    id: 30, channelName: "FinanceGuru PK", channelEmail: "financeguru.pk@gmail.com",
    primaryMail: "finance.guru.pk@gmail.com", category: "Finance",
    channelNiche: "Investment Tips", channelSubscribers: 98000,
    monetizationStatus: "Monetized", status: "pending",
    purchasePrice: 190000, salePrice: 290000, sellerName: "Imran Baig",
    createdAt: "2024-05-28", contentType: "Long-form",
    verificationStatus: true, views: 3800000, totalVideos: 155,
    brandName: "FinanceGuru", channelUrl: "youtube.com/financegurupk",
    ownershipStatus: "Changed",
  },
  {
    id: 31, channelName: "TechReviewsDaily", channelEmail: "techreviews.daily@gmail.com",
    primaryMail: "techreviews.owner@gmail.com", category: "Tech",
    channelNiche: "Daily Tech News", channelSubscribers: 142000,
    monetizationStatus: "Monetized", status: "pending",
    purchasePrice: 230000, salePrice: 350000, sellerName: "Faisal Anwar",
    createdAt: "2024-06-05", contentType: "Short-form",
    verificationStatus: true, views: 6500000, totalVideos: 430,
    brandName: "TechReviews", channelUrl: "youtube.com/techreviewsdaily",
    ownershipStatus: "Changed",
  },
  {
    id: 32, channelName: "IslamicStoriesPK", channelEmail: "islamicstories.pk@gmail.com",
    primaryMail: "islamic.stories.pk@gmail.com", category: "Education",
    channelNiche: "Islamic Stories", channelSubscribers: 175000,
    monetizationStatus: "Pending", status: "pending",
    purchasePrice: 260000, salePrice: 400000, sellerName: "Maulana Tariq",
    createdAt: "2024-05-15", contentType: "Long-form",
    verificationStatus: false, views: 7100000, totalVideos: 280,
    brandName: "IslamicStories", channelUrl: "youtube.com/islamicstoriespk",
    ownershipStatus: "Pending",
  },
  {
    id: 33, channelName: "FoodieStreetPK", channelEmail: "foodiestreet.pk@gmail.com",
    primaryMail: "foodie.street.pk@gmail.com", category: "Food",
    channelNiche: "Street Food", channelSubscribers: 215000,
    monetizationStatus: "Monetized", status: "pending",
    purchasePrice: 310000, salePrice: 460000, sellerName: "Naveed Khan",
    createdAt: "2024-06-22", contentType: "Short-form",
    verificationStatus: true, views: 9200000, totalVideos: 350,
    brandName: "FoodieStreet", channelUrl: "youtube.com/foodiestreetpk",
    ownershipStatus: "Changed",
  },
  {
    id: 34, channelName: "SportsArenaKhi", channelEmail: "sportsarena.khi@gmail.com",
    primaryMail: "sports.arena.khi@gmail.com", category: "Sports",
    channelNiche: "Sports Highlights", channelSubscribers: 88000,
    monetizationStatus: "Not Monetized", status: "pending",
    purchasePrice: 120000, salePrice: 185000, sellerName: "Shahid Afridi Jr",
    createdAt: "2024-07-01", contentType: "Short-form",
    verificationStatus: false, views: 3100000, totalVideos: 198,
    brandName: "SportsArena", channelUrl: "youtube.com/sportsarenakhi",
    ownershipStatus: "Pending",
  },
  {
    id: 35, channelName: "GamingPro786", channelEmail: "gamingpro786@gmail.com",
    primaryMail: "gamingpro.owner@gmail.com", category: "Gaming",
    channelNiche: "PUBG & COD", channelSubscribers: 390000,
    monetizationStatus: "Monetized", status: "pending",
    purchasePrice: 590000, salePrice: 850000, sellerName: "Zubair Malik",
    createdAt: "2024-06-30", contentType: "Long-form",
    verificationStatus: true, views: 18500000, totalVideos: 620,
    brandName: "GamingPro", channelUrl: "youtube.com/gamingpro786",
    ownershipStatus: "Changed",
  },
  // ── Additional sold channels ─────────────────────────────────────────────────
  {
    id: 36, channelName: "CricketFanaticsPK", channelEmail: "cricketfanatics.pk@gmail.com",
    primaryMail: "cricketfanatics.owner@gmail.com", category: "Sports",
    channelNiche: "Cricket Analysis", channelSubscribers: 285000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 430000, salePrice: 650000, sellerName: "Ahsan Iqbal",
    buyerName: "Zulfiqar Ali", buyerContact: "+92 307 1122334", soldAt: "2024-04-28",
    createdAt: "2024-01-12", contentType: "Short-form",
    verificationStatus: true, views: 13000000, totalVideos: 720,
    brandName: "CricketFanatics", channelUrl: "youtube.com/cricketfanaticspk",
  },
  {
    id: 37, channelName: "UrduDramaHub", channelEmail: "urdudrama.hub@gmail.com",
    primaryMail: "urdudrama.owner@gmail.com", category: "Entertainment",
    channelNiche: "Drama Reviews", channelSubscribers: 620000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 750000, salePrice: 1050000, sellerName: "Sadia Islam",
    buyerName: "Rana Azeem", buyerContact: "+92 341 9988776", soldAt: "2024-05-18",
    createdAt: "2024-02-05", contentType: "Short-form",
    verificationStatus: true, views: 38000000, totalVideos: 1600,
    brandName: "UrduDrama", channelUrl: "youtube.com/urdudramahub",
  },
  {
    id: 38, channelName: "MedicineTalkPK", channelEmail: "medicinetalk.pk@gmail.com",
    primaryMail: "medicinetalk.owner@gmail.com", category: "Education",
    channelNiche: "Health & Medicine", channelSubscribers: 110000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 175000, salePrice: 260000, sellerName: "Dr. Asim Raza",
    buyerName: "Irfan Pasha", buyerContact: "+92 320 5566778", soldAt: "2024-03-22",
    createdAt: "2024-01-18", contentType: "Long-form",
    verificationStatus: false, views: 4100000, totalVideos: 198,
    brandName: "MedicineTalk", channelUrl: "youtube.com/medicinetalkpk",
  },
  {
    id: 39, channelName: "NatureVlogsPK", channelEmail: "naturevlogs.pk@gmail.com",
    primaryMail: "naturevlogs.owner@gmail.com", category: "Lifestyle",
    channelNiche: "Nature & Wildlife", channelSubscribers: 88000,
    monetizationStatus: "Not Monetized", status: "sold",
    purchasePrice: 110000, salePrice: 155000, sellerName: "Khalid Mehmood",
    buyerName: "Nida Khan", buyerContact: "+92 318 4433221", soldAt: "2024-02-28",
    createdAt: "2024-01-25", contentType: "Long-form",
    verificationStatus: false, views: 2200000, totalVideos: 145,
    brandName: "NatureVlogs", channelUrl: "youtube.com/naturevlogspk",
  },
  {
    id: 40, channelName: "BusinessMasterPK", channelEmail: "businessmaster.pk@gmail.com",
    primaryMail: "businessmaster.owner@gmail.com", category: "Finance",
    channelNiche: "Business & Entrepreneurship", channelSubscribers: 195000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 310000, salePrice: 490000, sellerName: "Shoaib Akhtar",
    buyerName: "Asad Umar", buyerContact: "+92 313 7788990", soldAt: "2024-06-10",
    createdAt: "2024-02-15", contentType: "Long-form",
    verificationStatus: true, views: 8500000, totalVideos: 320,
    brandName: "BusinessMaster", channelUrl: "youtube.com/businessmasterpk",
  },
];