export const dummyStats = {
  totalSale: 2450000,
  totalPurchase: 1820000,
  totalProfit: 630000,
  totalChannels: 48,
  soldChannels: 31,
  availableChannels: 12,
  hackedChannels: 5,
};

export const monthlySalesData = [
  { month: "Jan", sales: 320000, purchases: 210000, profit: 110000 },
  { month: "Feb", sales: 280000, purchases: 190000, profit: 90000 },
  { month: "Mar", sales: 450000, purchases: 310000, profit: 140000 },
  { month: "Apr", sales: 390000, purchases: 270000, profit: 120000 },
  { month: "May", sales: 520000, purchases: 380000, profit: 140000 },
  { month: "Jun", sales: 490000, purchases: 460000, profit: 30000 },
];

export const recentChannels = [
  { id: 1, name: "TechVault PK", niche: "Technology", subscribers: "125K", salePrice: 380000, status: "sold" },
  { id: 2, name: "CookingWithNadia", niche: "Food", subscribers: "89K", salePrice: 210000, status: "available" },
  { id: 3, name: "CricketZone", niche: "Sports", subscribers: "340K", salePrice: 750000, status: "available" },
  { id: 4, name: "DailyVlogs786", niche: "Lifestyle", subscribers: "55K", salePrice: 130000, status: "sold" },
  { id: 5, name: "IslamicReminders", niche: "Religion", subscribers: "210K", salePrice: 490000, status: "available" },
];

export const navLinks = [
  { label: "Dashboard", icon: "LayoutDashboard", path: "/" },
  { label: "Channels", icon: "Video", path: "/channels" },
  { label: "Purchases", icon: "ShoppingCart", path: "/purchases" },
  { label: "Sales", icon: "TrendingUp", path: "/sales" },
  { label: "Reports", icon: "BarChart2", path: "/reports" },
  { label: "Hacked", icon: "ShieldAlert", path: "/hacked" },
];

export const channelsData = [
  {
    id: 1, channelName: "TechVault PK", channelEmail: "techvaultpk@gmail.com",
    primaryMail: "owner.techvault@gmail.com", category: "Tech",
    channelNiche: "Gadgets & Reviews", channelSubscribers: 125000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 280000, salePrice: 380000,
    createdAt: "2024-01-15", contentType: "Long-form",
    verificationStatus: true, views: 4200000, totalVideos: 312,
    brandName: "TechVault", channelUrl: "youtube.com/techvaultpk",
  },
  {
    id: 2, channelName: "CookingWithNadia", channelEmail: "cookingnadia@gmail.com",
    primaryMail: "nadia.kitchen@gmail.com", category: "Food",
    channelNiche: "Pakistani Recipes", channelSubscribers: 89000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 150000, salePrice: 210000,
    createdAt: "2024-02-03", contentType: "Long-form",
    verificationStatus: false, views: 2800000, totalVideos: 198,
    brandName: "Nadia Kitchen", channelUrl: "youtube.com/cookingnadia",
  },
  {
    id: 3, channelName: "CricketZone", channelEmail: "cricketzone.pk@gmail.com",
    primaryMail: "admin.cricketzone@gmail.com", category: "Sports",
    channelNiche: "Cricket Highlights", channelSubscribers: 340000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 550000, salePrice: 750000,
    createdAt: "2024-01-22", contentType: "Short-form",
    verificationStatus: true, views: 18000000, totalVideos: 870,
    brandName: "CricketZone", channelUrl: "youtube.com/cricketzonepk",
  },
  {
    id: 4, channelName: "DailyVlogs786", channelEmail: "dailyvlogs786@gmail.com",
    primaryMail: "vlogs786@gmail.com", category: "Lifestyle",
    channelNiche: "Daily Life", channelSubscribers: 55000,
    monetizationStatus: "Not Monetized", status: "hacked",
    purchasePrice: 90000, salePrice: 130000,
    createdAt: "2024-03-10", contentType: "Long-form",
    verificationStatus: false, views: 980000, totalVideos: 245,
    brandName: "Vlogs786", channelUrl: "youtube.com/dailyvlogs786",
  },
  {
    id: 5, channelName: "IslamicReminders", channelEmail: "islamicreminders@gmail.com",
    primaryMail: "islamic.channel@gmail.com", category: "Education",
    channelNiche: "Islamic Content", channelSubscribers: 210000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 320000, salePrice: 490000,
    createdAt: "2024-02-18", contentType: "Long-form",
    verificationStatus: true, views: 9500000, totalVideos: 432,
    brandName: "Islamic Reminders", channelUrl: "youtube.com/islamicreminderspk",
  },
  {
    id: 6, channelName: "GamersArena", channelEmail: "gamersarena.pk@gmail.com",
    primaryMail: "arena.gaming@gmail.com", category: "Gaming",
    channelNiche: "Mobile Gaming", channelSubscribers: 480000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 700000, salePrice: 950000,
    createdAt: "2024-01-08", contentType: "Long-form",
    verificationStatus: true, views: 22000000, totalVideos: 560,
    brandName: "GamersArena", channelUrl: "youtube.com/gamersarenapk",
  },
  {
    id: 7, channelName: "FinanceTips PK", channelEmail: "financetips.pk@gmail.com",
    primaryMail: "finance.tips.pk@gmail.com", category: "Finance",
    channelNiche: "Personal Finance", channelSubscribers: 72000,
    monetizationStatus: "Pending", status: "available",
    purchasePrice: 120000, salePrice: 175000,
    createdAt: "2024-04-02", contentType: "Long-form",
    verificationStatus: false, views: 1800000, totalVideos: 134,
    brandName: "FinanceTips", channelUrl: "youtube.com/financetipspk",
  },
  {
    id: 8, channelName: "EntertainMe PK", channelEmail: "entertainmepk@gmail.com",
    primaryMail: "entertain.me.pk@gmail.com", category: "Entertainment",
    channelNiche: "Comedy Skits", channelSubscribers: 1200000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 1200000, salePrice: 1800000,
    createdAt: "2024-01-30", contentType: "Short-form",
    verificationStatus: true, views: 85000000, totalVideos: 2100,
    brandName: "EntertainMe", channelUrl: "youtube.com/entertainmepk",
  },
  {
    id: 9, channelName: "FitnessFirst PK", channelEmail: "fitnessfirst.pk@gmail.com",
    primaryMail: "fitness.first.owner@gmail.com", category: "Lifestyle",
    channelNiche: "Workout & Health", channelSubscribers: 95000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 160000, salePrice: 240000,
    createdAt: "2024-03-25", contentType: "Long-form",
    verificationStatus: false, views: 3400000, totalVideos: 287,
    brandName: "FitnessFirst", channelUrl: "youtube.com/fitnessfirstpk",
  },
  {
    id: 10, channelName: "KidsLearningHub", channelEmail: "kidslearning.hub@gmail.com",
    primaryMail: "kids.hub.owner@gmail.com", category: "Education",
    channelNiche: "Kids Education", channelSubscribers: 670000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 800000, salePrice: 1100000,
    createdAt: "2024-02-10", contentType: "Long-form",
    verificationStatus: true, views: 42000000, totalVideos: 920,
    brandName: "KidsHub", channelUrl: "youtube.com/kidslearninghub",
  },
  {
    id: 11, channelName: "TravelPakistan", channelEmail: "travelpakistan@gmail.com",
    primaryMail: "travel.pk.owner@gmail.com", category: "Lifestyle",
    channelNiche: "Travel & Tourism", channelSubscribers: 135000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 220000, salePrice: 320000,
    createdAt: "2024-04-15", contentType: "Long-form",
    verificationStatus: false, views: 5200000, totalVideos: 198,
    brandName: "TravelPK", channelUrl: "youtube.com/travelpakistan",
  },
  {
    id: 12, channelName: "MusicVibes PK", channelEmail: "musicvibes.pk@gmail.com",
    primaryMail: "musicvibes.owner@gmail.com", category: "Entertainment",
    channelNiche: "Music & Covers", channelSubscribers: 520000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 600000, salePrice: 850000,
    createdAt: "2024-01-05", contentType: "Short-form",
    verificationStatus: true, views: 31000000, totalVideos: 1450,
    brandName: "MusicVibes", channelUrl: "youtube.com/musicvibespk",
  },
  {
    id: 13, channelName: "NewsFlashPK", channelEmail: "newsflash.pk@gmail.com",
    primaryMail: "newsflash.admin@gmail.com", category: "Entertainment",
    channelNiche: "News & Current Affairs", channelSubscribers: 890000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 950000, salePrice: 1350000,
    createdAt: "2024-03-01", contentType: "Short-form",
    verificationStatus: true, views: 67000000, totalVideos: 3200,
    brandName: "NewsFlash", channelUrl: "youtube.com/newsflashpk",
  },
  {
    id: 14, channelName: "ChefKamran", channelEmail: "chefkamran.official@gmail.com",
    primaryMail: "kamran.chef@gmail.com", category: "Food",
    channelNiche: "BBQ & Grilling", channelSubscribers: 48000,
    monetizationStatus: "Not Monetized", status: "available",
    purchasePrice: 60000, salePrice: 90000,
    createdAt: "2024-05-10", contentType: "Long-form",
    verificationStatus: false, views: 820000, totalVideos: 87,
    brandName: "Chef Kamran", channelUrl: "youtube.com/chefkamran",
  },
  {
    id: 15, channelName: "PSLHighlights", channelEmail: "psl.highlights@gmail.com",
    primaryMail: "psl.official.channel@gmail.com", category: "Sports",
    channelNiche: "PSL Cricket", channelSubscribers: 2000000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 1500000, salePrice: 2000000,
    createdAt: "2024-01-01", contentType: "Short-form",
    verificationStatus: true, views: 200000000, totalVideos: 5600,
    brandName: "PSL Highlights", channelUrl: "youtube.com/pslhighlights",
  },
  {
    id: 16, channelName: "AutoZonePK", channelEmail: "autozone.pk@gmail.com",
    primaryMail: "autozone.admin@gmail.com", category: "Tech",
    channelNiche: "Cars & Bikes", channelSubscribers: 165000,
    monetizationStatus: "Monetized", status: "hacked",
    purchasePrice: 250000, salePrice: 380000,
    createdAt: "2024-02-28", contentType: "Long-form",
    verificationStatus: true, views: 7800000, totalVideos: 345,
    brandName: "AutoZone", channelUrl: "youtube.com/autozonepk",
  },
  {
    id: 17, channelName: "QuranInUrdu", channelEmail: "quranurdu@gmail.com",
    primaryMail: "quran.urdu.owner@gmail.com", category: "Education",
    channelNiche: "Quran Translation", channelSubscribers: 380000,
    monetizationStatus: "Pending", status: "available",
    purchasePrice: 400000, salePrice: 580000,
    createdAt: "2024-04-20", contentType: "Long-form",
    verificationStatus: true, views: 14500000, totalVideos: 620,
    brandName: "QuranUrdu", channelUrl: "youtube.com/quranurdu",
  },
  {
    id: 18, channelName: "ComedyKlub", channelEmail: "comedyklub.pk@gmail.com",
    primaryMail: "comedy.klub@gmail.com", category: "Entertainment",
    channelNiche: "Pakistani Comedy", channelSubscribers: 750000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 850000, salePrice: 1200000,
    createdAt: "2024-02-14", contentType: "Short-form",
    verificationStatus: true, views: 55000000, totalVideos: 1890,
    brandName: "ComedyKlub", channelUrl: "youtube.com/comedyklubpk",
  },
  {
    id: 19, channelName: "UrduPoetry", channelEmail: "urdupoetry.official@gmail.com",
    primaryMail: "poetry.urdu.owner@gmail.com", category: "Entertainment",
    channelNiche: "Poetry & Shayari", channelSubscribers: 220000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 300000, salePrice: 440000,
    createdAt: "2024-05-05", contentType: "Short-form",
    verificationStatus: false, views: 10200000, totalVideos: 780,
    brandName: "Urdu Poetry", channelUrl: "youtube.com/urdupoetry",
  },
  {
    id: 20, channelName: "MobileWorldPK", channelEmail: "mobileworld.pk@gmail.com",
    primaryMail: "mobile.world.owner@gmail.com", category: "Tech",
    channelNiche: "Smartphone Reviews", channelSubscribers: 195000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 290000, salePrice: 420000,
    createdAt: "2024-03-18", contentType: "Long-form",
    verificationStatus: true, views: 8900000, totalVideos: 412,
    brandName: "MobileWorld", channelUrl: "youtube.com/mobileworldpk",
  },
  {
    id: 21, channelName: "FarmingWithAli", channelEmail: "farmingwithali@gmail.com",
    primaryMail: "ali.farming@gmail.com", category: "Other",
    channelNiche: "Modern Farming", channelSubscribers: 32000,
    monetizationStatus: "Not Monetized", status: "available",
    purchasePrice: 45000, salePrice: 70000,
    createdAt: "2024-06-01", contentType: "Long-form",
    verificationStatus: false, views: 540000, totalVideos: 65,
    brandName: "FarmingAli", channelUrl: "youtube.com/farmingwithali",
  },
  {
    id: 22, channelName: "GamingBattleground", channelEmail: "gamingbg.pk@gmail.com",
    primaryMail: "gaming.bg@gmail.com", category: "Gaming",
    channelNiche: "FPS Gaming", channelSubscribers: 310000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 420000, salePrice: 620000,
    createdAt: "2024-04-08", contentType: "Long-form",
    verificationStatus: true, views: 15600000, totalVideos: 498,
    brandName: "BattlegroundPK", channelUrl: "youtube.com/gamingbattleground",
  },
  {
    id: 23, channelName: "DIYHomeDecor", channelEmail: "diyhome.pk@gmail.com",
    primaryMail: "diy.homedecor@gmail.com", category: "Lifestyle",
    channelNiche: "Home Decoration", channelSubscribers: 68000,
    monetizationStatus: "Pending", status: "available",
    purchasePrice: 95000, salePrice: 145000,
    createdAt: "2024-05-20", contentType: "Long-form",
    verificationStatus: false, views: 1900000, totalVideos: 143,
    brandName: "DIYHome", channelUrl: "youtube.com/diyhomepk",
  },
  {
    id: 24, channelName: "CryptoTalkPK", channelEmail: "cryptotalk.pk@gmail.com",
    primaryMail: "crypto.pk.owner@gmail.com", category: "Finance",
    channelNiche: "Crypto & Blockchain", channelSubscribers: 115000,
    monetizationStatus: "Monetized", status: "hacked",
    purchasePrice: 180000, salePrice: 270000,
    createdAt: "2024-03-05", contentType: "Long-form",
    verificationStatus: false, views: 4400000, totalVideos: 228,
    brandName: "CryptoTalk", channelUrl: "youtube.com/cryptotalkpk",
  },
  {
    id: 25, channelName: "KarachiStreetFood", channelEmail: "karachistreet@gmail.com",
    primaryMail: "karachi.food.admin@gmail.com", category: "Food",
    channelNiche: "Street Food Tours", channelSubscribers: 430000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 520000, salePrice: 780000,
    createdAt: "2024-01-28", contentType: "Short-form",
    verificationStatus: true, views: 28000000, totalVideos: 920,
    brandName: "KarachiFood", channelUrl: "youtube.com/karachistreetfood",
  },
  {
    id: 26, channelName: "EduMathPK", channelEmail: "edumath.pk@gmail.com",
    primaryMail: "math.edu.owner@gmail.com", category: "Education",
    channelNiche: "Math & Science", channelSubscribers: 155000,
    monetizationStatus: "Monetized", status: "available",
    purchasePrice: 220000, salePrice: 330000,
    createdAt: "2024-06-15", contentType: "Long-form",
    verificationStatus: true, views: 6200000, totalVideos: 375,
    brandName: "EduMath", channelUrl: "youtube.com/edumathpk",
  },
  {
    id: 27, channelName: "BeautyByZara", channelEmail: "beautyzara.pk@gmail.com",
    primaryMail: "zara.beauty@gmail.com", category: "Lifestyle",
    channelNiche: "Beauty & Makeup", channelSubscribers: 260000,
    monetizationStatus: "Monetized", status: "sold",
    purchasePrice: 350000, salePrice: 510000,
    createdAt: "2024-02-22", contentType: "Long-form",
    verificationStatus: false, views: 12000000, totalVideos: 310,
    brandName: "BeautyZara", channelUrl: "youtube.com/beautybyzara",
  },
];